general:
  enable_incomplete_verification: false
  root_path: ${CONFIG_PATH}/..
  csv_name: specs/quadrotor2d.csv
  save_adv_example: true
model:
  name: >-
    Customized(
      "models/control.py", "ModelControl",
      dynamics="quadrotor2d", controller_width=8, controller_depth=2,
      lyapunov_eps=1e-8, lyapunov_R_rows=6, verification=True,
    )
  input_shape: [-1, 6]
attack:
  pgd_order: before
  pgd_restarts: 10000
  pgd_alpha: 0.1
  pgd_alpha_scale: True
solver:
  batch_size: 3000000
  min_batch_size_ratio: 0.
  bound_prop_method: crown
bab:
  override_timeout: 3000
  sort_domain_interval: -1
  branching:
    method: sb  # Can be "naive" or "sb". "sb" is usually better.
    input_split:
      enable: True
      ibp_enhancement: True
      compare_with_old_bounds: True
      sb_coeff_thresh: 1.e-2
      sb_sum: True
      touch_zero_score: 0.1
      adv_check: -1
      sort_descending: False